# Site Details
site_name: Alternate Guides
site_url: https://skrillx13.github.io/Alternate-Guides/
site_author: Skrillx
site_description: >-
  A guide to the Minecraft Modpack "Alternate World". Progress through the Modpack easily with this guide.

# Repository
repo_name: Alternate Guides
repo_url: https://github.com/Skrillx13/Alternate-Guides

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/Skrillx13/Alternate-Guides"  target="_blank" rel="noopener">Alternate Guides</a> | Made By <a href='https://beacons.ai/skrillx' target='_blank' class='cauthor'>Skrillx</a> | Hosted on <a href='https://pages.github.com' target='_blank' class='cauthor'>GitHub Pages</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-5
        name: Enable Dark Mode
      primary: dark blue
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/brightness-2
        name: Enable Light Mode    
      primary: black
      accent: lime
  font: 
    text: "roboto-condensed"
    code: Roboto Mono
  icon: 
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/images/alternateworldicon.png
  favicon: assets/images/anvil.png
  language: en

# Extra Configurations
extra:
   social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/Skrillx_13
      name: Tweeter
    - icon: fontawesome/brands/github
      link: https://github.com/Skrillx13
      name: GitHub
    - icon: fontawesome/brands/flickr
      link: https://beacons.ai/skrillx
      name: Linktree

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Navigation
nav:
  - Home: index.md
  - Getting Started: 
    - Installation: gettingstarted/installation.md
  - AW1:
    - aw1/index.md
    - Getting Started: aw1/gettingstarted.md
  - AW2: 
    - aw2/index.md
    - Getting Started: aw2/gettingstarted.md
  - Contibution: 
    - contribution/index.md
    - Guidelines: contribution/guidelines.md
  - Extras: 
    - extras/index.md
  - Help:
    - help/index.md
    - FAQ: help/faq.md