site_name: Alternate Guides
site_url: https://skrillx13.github.io/Alternate-Guides/
site_author: Skrillx
site_description: >-
  A guide to the Minecraft Modpack "Alternate World"
repo_url: https://github.com/Skrillx13/Alternate-Guides
repo_name: Alternate Guides
extra:
   social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/Skrillx_13
      name: Tweeter
    - icon: fontawesome/brands/github
      link: https://github.com/Skrillx13
      name: GitHub
    - icon: fontawesome/brands/flickr
      link: https://beacons.ai/skrillx
      name: Linktree

theme:
  name: material
  features:
    - toc.follow
    - toc.integrate
    - navigation.path
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Enable Dark Mode
      primary: teal
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Enable Light Mode    
      primary: teal
      accent: lime
  icon: 
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/images/alternateworldicon.png
  font:
    text: "roboto-condensed"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-2
        name: Enable Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: cyan
      toggle:
        icon: material/brightness-5
        name: Enable Light Mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: |
  &copy; 2024 <a href="https://github.com/Skrillx13/Alternate-Guides"  target="_blank" rel="noopener">Alternate Guides</a> | Made By <a href='https://beacons.ai/skrillx' target='_blank' class='cauthor'>Skrillx</a> | Hosted on <a href='https://pages.github.com' target='_blank' class='cauthor'>GitHub Pages</a>